import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TfiArrowTopRight } from "react-icons/tfi";
import Link from "next/link";
import { TiSocialFacebook } from "react-icons/ti";
import { FaFacebookF, FaSquareInstagram, FaXTwitter } from "react-icons/fa6";
import { FaLinkedinIn, FaYoutube } from "react-icons/fa";
import 'bootstrap/dist/css/bootstrap.css';
import "bootstrap-icons/font/bootstrap-icons.css";
import Footer from "@/components/Footer";
import Head from "next/head";
import "./globals.css";
import "./responsive.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import "react-datepicker/dist/react-datepicker.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "squch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
    <html lang="en">
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="dashboardPage">
          <Header />
          <div className="d-flex dashboard-main">
            <div className="side-menu-sec-main position-relative">
              <SideBar />
            </div>
            <div className="right-pages">
              <div className="inner-dashboard-pages">
                {children}
              </div>
            </div>
          </div>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  </>);
}
